### ISSUE TITLE
Update-ZoomUser missing some attributes supported by the API

### ISSUE THREAD

**Issue by diggityshmoo** [JosephMcEvoy/PSZoom#10]
The zoom API (https://marketplace.zoom.us/docs/api-reference/zoom-api/users/userupdate) supports some attributes that are not currently implemented in Update-ZoomUser

* job_title
* company
* location
* phone_number
* phone_country

I assume the API was updated to add these at some point.  It would be helpful if they were incorporated into the module.  Thanks!

**Comment by JosephMcEvoy** [comment]
Hi,

Thank you for pointing that out. You are welcome to open a pull request and update the function.
