### ISSUE TITLE
Error when creating new users: "Invalid URI: The hostname could not be parsed."

### ISSUE THREAD

**Issue by I-FGSD** [JosephMcEvoy/PSZoom#101]
I'm using PSZoom 2.0.4.1

The connect and the get commands work fine... it's when I try new-zoomuser that I noticed this new issue (it worked fine a few weeks ago):

new-zoomuser -action ssoCreate -email $($emailAddress) -Type 1 -FirstName $($firstName) -LastName $($lastName)

`
Cannot convert value "https://api.$ZoomURI/v2/users" to type "System.UriBuilder". Error: "Invalid URI: The hostname could not be parsed."
At C:\Program Files\WindowsPowerShell\Modules\pszoom\2.0.4.1\Public\Users\New-ZoomUser.ps1:91 char:9
         $request = [System.UriBuilder]'https://api.$ZoomURI/v2/users'
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidArgument: (:) [], RuntimeException
     FullyQualifiedErrorId : InvalidCastConstructorException
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\pszoom\2.0.4.1\Public\Utils\Invoke-ZoomRestMethod.ps1:146 char:13
             $errorStreamReader = [System.IO.StreamReader]::new($_.exc ...
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidOperation: (:) [], RuntimeException
     FullyQualifiedErrorId : InvokeMethodOnNull
`

Any ideas on what's going on? It used to work just fine, so I'm not sure what changed?

Thank you.

**Comment by I-FGSD** [comment]
Any updates for this issue? Am I the only one experiencing this?

**Comment by SpectreGadgetReborn** [comment]
I'm seeing the same thing with 2.0.4.1
