### ISSUE TITLE
404 Error Removing Users

### ISSUE THREAD

**Issue by AstroFish849** [JosephMcEvoy/PSZoom#109]
Hi, I'm able to add users with no issues using powershell but when using powershell to remove users I get the below:

Invoke-ZoomRestMethod : The remote server returned an error: (404) Not Found. 
At C:\Users\xxx\Documents\WindowsPowerShell\Modules\PSZoom\2.1\Public\Users\Remove-ZoomUser.ps1:120 char:29
+ ...    $response = Invoke-ZoomRestMethod -Uri $request.Uri -Method DELETE
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (https://api.zoo...er_meeting=true:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : 404,Invoke-ZoomRestMethod

**Comment by andrew-hoggins** [comment]
@AstroFish849,

For the -UserId argument, did you supply an email address or ZoomUserID?
Are you able to use the get-zoomuser -UserId cmdlet to view the user's settings or do you get a 404 as well?

**Comment by AstroFish849** [comment]
> @AstroFish849,
> 
> For the -UserId argument, did you supply an email address or ZoomUserID? Are you able to use the get-zoomuser -UserId cmdlet to view the user's settings or do you get a 404 as well?
> 
> 404 indicates that the resource you are attempting to locate does not exist.

I've just tried the get-zoomuser -UserID with the email address and it's working fine
I've also just tried the remove-zoomuser with both the users email and the ID and get the same 404 error

**Comment by andrew-hoggins** [comment]
> I've just tried the get-zoomuser -UserID with the email address and it's working fine I've also just tried the remove-zoomuser with both the users email and the ID and get the same 404 error

I don't see anything wrong with the how the function logic is working.
Tested on 2.1 release and was able to delete users via UserID and email.
Can you verify your API token has the following permission scopes?
<br>
Scopes: user:write:admin,user:write

**Comment by AstroFish849** [comment]
Just as a test, i've tried it on a machine at home to make sure something wasn't getting blocked by a firewall and it still failed with the same error

**Comment by andrew-hoggins** [comment]
How was the user created and what login method do they use?

**Comment by AstroFish849** [comment]
The user was created using the same Zoom API
 New-ZoomUser -Action create -Email "firstname.lastname@domain.com" -FirstName "Firstname" -LastName "Lastname" -Type 1 -Password "Password"

**Comment by andrew-hoggins** [comment]
Ok, I think I was able to reproduce the error.
Was the user you were attempting to delete listed under the "Pending" tab?
![image](https://github.com/JosephMcEvoy/PSZoom/assets/130623917/190d409e-c2be-45c1-b615-293731342b9b)


I noticed that if the account hasn't been activated by the user, the get-zoomuser command can locate them, but the remove-zoomuser command cannot.  Once user is activated you can delete without issue.
Let me see if there is a way to delete the pending accounts created via API.

**Comment by andrew-hoggins** [comment]
Ok I see the issue, the module will add a query parameter to API request even if there are no queries.
This somehow breaks deleting a pending user as by commenting out the query parameter on the request allowed me to delete pending users.
I will submit a fix soon.
