### ISSUE TITLE
[Proposal] New-ZoomApiToken 

### ISSUE THREAD

**Issue by mkht** [JosephMcEvoy/PSZoom#11]
Hi @JosephMcEvoy 

I'm very impressed with this project!
I'm currently working on the management of Zoom in my org, and your module has helped me a lot. 👍 

So, my proposal is to add a cmdlet to generate a Zoom API token to the module.
It doesn't essentially execute the API, but it could be useful when we want to directly execute the Zoom API for testing purposes.
It's not so difficult to implement because it only cuts out a part of the process `New-ZoomHeader` is currently doing in the module.
I will open a PR for you to consider.

Thank you,

**Comment by JosephMcEvoy** [comment]
Hi mkht,

I'm glad you have found the module useful. I have reviewed your code. It looks good. What is an example of how you would use this?

**Comment by mkht** [comment]
For example, if we want to try out an API that is not yet implemented in PSZoom, we can paste the token generated by New-ZoomApiToken into the Zoom API Reference and execute it.

![zoom](https://user-images.githubusercontent.com/25482642/84020203-682e4f80-a9bd-11ea-8219-e68062657137.png)

Also, this is a future request, but I would like to add a `-Token` parameter to the PSZoom cmdlets. This would give the user the option to bypass the default token period of 30 seconds.
```PowerShell
<#=== This is a future request, not yet implmented. ===#>
#Generate 1 hour token
$Token = New-ZoomApiToken -ApiKey $k -ApiSecret $s -ValidforSeconds 3600
#Execute commands that are expected to take more than 30 seconds
$VeryLargeNumberOfUsers = Get-ZoomUsers -AllPages -Token $Token
```

**Comment by JosephMcEvoy** [comment]
This has been pushed to Powershell Gallery.
