### ISSUE TITLE
Get-ZoomUsers -Status All

### ISSUE THREAD

**Issue by nascentt** [JosephMcEvoy/PSZoom#112]
I didn't realize that by not specifying a status it's still restricted to active, so my scripts checking for user status was redundant as they were all active.

Currently I need to manually check 
Get-ZoomUsers -Status active
Get-ZoomUsers -Status inactive
Get-ZoomUsers -Status pending to ensure I have all statuses.  
It'd be great to get an All status option (which in my opinion should be the default)

**Comment by andrew-hoggins** [comment]
I like this idea!  It is more powershell native behavior.

**Comment by nascentt** [comment]
I just got a chance to test this change out.  Now that get-zoomusers is an alias for get-zoomuser the -AllPages parameter is gone.

Does that mean all pages are returned by default. Or do we need to implement pagination for calls to Get-ZoomUser now?
