### ISSUE TITLE
Where is OAuth on Zoom marketplace

### ISSUE THREAD

**Issue by NagromCurse** [JosephMcEvoy/PSZoom#113]
Hi!
I'd like to try the PSZoom modules but I cannot find the option to create a Server-to-Server OAuth key/secret on the https://marketplace.zoom.us/develop/create page you are referring to.

**Comment by jjpaq** [comment]
How far did you get? This is the dialog I see when I go to that URL:
![image](https://github.com/JosephMcEvoy/PSZoom/assets/55399772/4754afc0-5610-48e1-b4eb-8124dacc7496)

I didn't want to create an entire app just to test the setup flow, but if you get stuck after that I can try getting to the same spot.

**Comment by jjpaq** [comment]
(if you don't see the same popup, there's also this 'Develop' menu at the top-right)
![image](https://github.com/JosephMcEvoy/PSZoom/assets/55399772/50230d23-c83d-4f1a-a1c2-10fda2e73ea4)

**Comment by NagromCurse** [comment]
I see the "Develop" menu.
What do I pick there in order to generate a secret for this command:

Connect-PSZoom -AccountID 'account_id' -ClientID 'client_id' -ClientSecret 'secret'

**Comment by andrew-hoggins** [comment]
As mentioned on readme, please create a "Server-to-Server OAuth".

## Using your API key and API secret ##
All commands require a Client ID and Client Secret. As of PSZoom 2.0, PSZoom only supports Server-to-Server OAuth authorization. You can generate the Server-to-Server OAuth key/secret from https://marketplace.zoom.us/develop/create, then click on  'Create' under Server-to-Server OAuth.  

1. Under "Develop" choose option to "Build App"
![image](https://github.com/JosephMcEvoy/PSZoom/assets/130623917/f26d848c-386a-46e5-ae7e-b9b4bec758a4)

2. Locate and create a "Server-to-server OAuth"
![image](https://github.com/JosephMcEvoy/PSZoom/assets/130623917/278b9ac5-f426-4981-be53-10f89ce7a222)

3. Enter a name then locate [scopes] and select "+ Add Scopes"
![image](https://github.com/JosephMcEvoy/PSZoom/assets/130623917/0eb9734e-9d4d-4795-9c03-909c0df21fb6)

4. Add all the required permissions
![image](https://github.com/JosephMcEvoy/PSZoom/assets/130623917/21361399-2b06-41e6-af81-535d01e5da08)

5. Activate app.

6. You can then use App Credentials using the connect-pszoom command.  
##Please keep credentials sfae!##

**Comment by NagromCurse** [comment]
Thanks for the clarification!
