### ISSUE TITLE
401 Unauthorized 

### ISSUE THREAD

**Issue by thebrickerbackribs** [JosephMcEvoy/PSZoom#13]
I am running a query to pull all users and am getting a 401 unauthorized. I am an admin in Zoom (not the owner). I just pulled the secret and key from Zoom admin console under personal/settings. We have over 800 users and I have tried

#In Powershell it’s explicitly written as a string for the key and secret
$apiKey = ‘’
$apiSecret = '’

Get-ZoomUsers -AllPages -ApiKey $apiKey -ApiSecret $apiSecret
Get-ZoomUsers : The remote server returned an error: (401) Unauthorized.
At line:1 char:1

Get-ZoomUsers -AllPages -ApiKey $apiKey -ApiSecret $apiSecret
  + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
  + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-ZoomUsers

Get-ZoomUsers : The remote server returned an error: (401) Unauthorized.
At C:\Program Files\WindowsPowerShell\Modules\pszoom\1.1.8\Public\Users\Get-ZoomUsers.ps1:181 char:27

… ageCount = (Get-ZoomUsers -PageSize 300 @params -FullApiResponse).pag …
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : InvalidOperation: (:slight_smile: [Write-Error], WriteErrorException
FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-ZoomUsers
Separate Instance

Get-ZoomUsers -PageNumber 1 -ApiKey $apiKey -ApiSecret $apiSecret
Get-ZoomUsers : The remote server returned an error: (401) Unauthorized.
At line:1 char:1

Get-ZoomUsers -PageNumber 1 -ApiKey $apiKey -ApiSecret $apiSecret
  + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
  + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-ZoomUsers

**Comment by JosephMcEvoy** [comment]
I go to Advanced > App Marketplace > Manage ([https://marketplace.zoom.us/user/build](https://marketplace.zoom.us/user/build)) to generate the key/secret. I am logged in as an admin account. The admin role will need the Zoom for developers - Build and publish apps on Marketplace permissions enabled. This is very likely not an issue with PSZoom but your Zoom individual Zoom account or overall account configuration.
