### ISSUE TITLE
Update Module

### ISSUE THREAD

**Issue by AllElbows** [JosephMcEvoy/PSZoom#15]
Hi. No idea if I have done this right but i added 2 more functions for Zoom Rooms. 
List-ZoomRooms
List-ZoomRoomDevices

I want to add another but am not sure of the name to use. 
https://marketplace.zoom.us/docs/api-reference/zoom-api/dashboards/dashboardzoomrooms

I will use List-DashboardZoomRooms unless someone suggests something else.

**Comment by AllElbows** [comment]
#14 
These are the 2 new functions.

**Comment by JosephMcEvoy** [comment]
#14 Correct me if I'm wrong -- List-ZoomRooms is the same cmdlet as Get-ZoomRooms, no? Looks like Zoom updated this API. You could open up a pull request to update the existing cmdlet. Do use [PowerShell approved verbs](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7). The cmdlets mentioned should all use _Get_.  

Looks like you you're keeping with the style of the project (much appreciated). Something that is inconsistent across PSZoom's cmdlets is variable capitalization. Parameters should be capitalized while everything else should be camel case. Just being a bit nitpicky there but can be easier to read. This is a Powershell convention that you can read more about [here](https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/strongly-encouraged-development-guidelines?view=powershell-7). I am still to update this across all cmdlets...

**Comment by AllElbows** [comment]
They are giving different outputs and as i didn't know the use case for the other I just left it. 
I only output as JSON as the get-zoomrooms was outputting as JSON so i did it to keep it in line.

**Comment by AllElbows** [comment]
Oh as for using list thats what it was called in the API and you obviously already had 'Get-ZoomRooms'. Feel free to rename them as you see fit.

**Comment by AllElbows** [comment]
Added last one for today and called it Get-DashboardZoomRooms. I removed the convertto-json so now it spits out a object. Will you update the others?
Also, I have never worked on someone elses github project before so if i mess anything up just let me know.

**Comment by DamagedDingo** [comment]
What happened to Get-DashboardZoomRooms?
Was it removed on purpose?
