### ISSUE TITLE
Cloud Recordings

### ISSUE THREAD

**Issue by jtwaddlegus** [JosephMcEvoy/PSZoom#18]
Thank you for writing this module.  I just started testing out PSZoom.  I am looking for a way to get Cloud recording usage and pull down cloud recordings so I can put them on Google Drive.  When I try to call "Get-ZoomMeetingCloudRecordings", I get an error that this cmdlet/function does not exist.  Any idea why this would happen.  The other cmdlets seem to be working.

**Comment by jtwaddlegus** [comment]
I believe we would need access to this api call to get the info we wanted.  https://marketplace.zoom.us/docs/api-reference/zoom-api/cloud-recording/getaccountcloudrecording
I don't think this has been implemented as of yet in this module.

**Comment by jtwaddlegus** [comment]
I was able to get what I needed by using Get-ZoomAccountRecordings.  Thank you!

**Comment by plylechapman** [comment]
@jtwaddlegus Would you be willing to share your code for downloading the recordings?  At first glance I don't see this possible with "Get-ZoomAccountRecordings" natively.

**Comment by JosephMcEvoy** [comment]
Maybe something like this:
$recordings = Get-ZoomAccountRecordings me -From 2020-01-01 -To 2020-05-04 | select meetings
$downloadURLs = $recordings.psobject.properties.value.recording_files.download_url
$downloadURLs

Then pipe or loop through downloadURLs using invoke-webrequest or Start-BitsTransfer.

**Comment by jtwaddlegus** [comment]
I just did something like this.  Just had to start with some date and increment until today...

function getAllZoomRecordings(){
    #get all cloud recordings #Their api function only does 30 days so had to do 30 days at a time..
    $dateStart = get-date -Year '2019' -Month '01' -Day '01'
    $dateFinalEnd = Get-Date
    $dateAdd = 30
    $zoomMeetingRecordings = @()

    $dateEnd = $dateStart.AddDays($dateAdd)
    while($dateEnd -lt $dateFinalEnd.AddDays($dateAdd)){
        $zoomRecordingsReturn = Get-ZoomAccountRecordings -AccountId me -From $dateStart.ToString('yyyy-MM-dd') -To $dateEnd.ToString('yyyy-MM-dd')  -PageSize 300
        $zoomMeetingRecordings += $zoomRecordingsReturn.meetings
        while($zoomRecordingsReturn.next_page_token){
            $zoomRecordingsReturn = Get-ZoomAccountRecordings -AccountId me -From $dateStart.ToString('yyyy-MM-dd') -To $dateEnd.ToString('yyyy-MM-dd') -PageSize 300 -NextPageToken $zoomRecordingsReturn.next_page_token
            $zoomMeetingRecordings += $zoomRecordingsReturn.meetings
        }
        $dateStart = $dateEnd.AddDays(1)
        $dateEnd = $dateEnd.AddDays($dateAdd)
    }

    #$zoomMeetingRecordings.count
    return $zoomMeetingRecordings
}

**Comment by jtwaddlegus** [comment]
and like @JosephMcEvoy  said just used Start-BitsTransfer to download.

**Comment by plylechapman** [comment]
Awesome, thank you both.  One last question -if we had to pass the authorization to download a password-protected recording, can I use Start-BitsTransfer or do I have to do something else?  I am trying to do this for thousands of accounts and some will be most certainly password protected.

I see this in the notes:

To access a password protected cloud recording, add an “access_token” parameter to the download URL and provide
JWT as the value of the “access_token”.

**Comment by plylechapman** [comment]
Oh wait, maybe I figured it out - it's just a querystring appended with the actual JWT access token.  Nevermind..thanks again!
