### ISSUE TITLE
Cant install via Install-Module

### ISSUE THREAD

**Issue by pompushko** [JosephMcEvoy/PSZoom#2]
Hello

 **Install-Module PSZoom** cant install ;(
Windows 2016 \  PSVersion                      5.1.14393.3053 

> PS C:\Users\adm-user\Downloads> Install-Module PSZoom
> 
> WARNING: Source Location 'https://www.powershellgallery.com/api/v2/package/PSZoom/1.1.0' is not valid.
> PackageManagement\Install-Package : Package 'PSZoom' failed to download.
> At C:\Program Files (x86)\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
> + ...          $null = PackageManagement\Install-Package @PSBoundParameters
> +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ResourceUnavailable: (C:\Users\adm-us...om\PSZoom.nupkg:String) [Install-Package], Exception
>     + FullyQualifiedErrorId : PackageFailedInstallOrDownload,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage 
>

**Comment by JosephMcEvoy** [comment]
Hi,

It is working with me on PS 5.1.18362.628. Are you able to install other modules?

**Comment by pompushko** [comment]
hello Joseph

Yes....

**Comment by JosephMcEvoy** [comment]
Unless there are additional reports I believe the issue is with your local computer. I would suggest cloning from Github and importing manually.

**Comment by pompushko** [comment]
Strange...
This is help to me:
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 `


But, have second problem:

 PS C:\Windows\system32> C:\Scripts\PSZoom\PSZoom.ps1
VERBOSE: Retrieving Zoom API Credentials.
VERBOSE: Retrieved API Credentials.
VERBOSE: Generating JWT
VERBOSE: Generating Headers
VERBOSE: GET https://api.zoom.us/v2/users/USER@DOMAIN.com with 0-byte payload
Get-ZoomUser : The remote server returned an error: (401) Unauthorized.
At C:\Scripts\PSZoom\PSZoom.ps1:8 char:1
+ Get-ZoomUser -UserId "USER@DOMAIN.com" -ApiKey ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-ZoomUser 



I create application and get key and secret. Still nothing :(

**Comment by JosephMcEvoy** [comment]
Make sure you are copying the key and secret. Zoom also has an IM chat key which I have seen get confused with the key/secret.

**Comment by pompushko** [comment]
Copied many times ;(

IM chat key i need?

**Comment by pompushko** [comment]
Today i try do that on different workstation and same problem. But instillation was good and without any problems

`Get-ZoomUser : The remote server returned an error: (401) Unauthorized.`

**Comment by JosephMcEvoy** [comment]
Do not use IM Chat history token. If you are using the correct key/secret maybe it is an issue with Zoom / you are not set up to use the API?

**Comment by pompushko** [comment]
@JosephMcEvoy i create JWT app and all fine from Zoom side

![image](https://user-images.githubusercontent.com/20593903/78685532-89f65200-78fa-11ea-876d-f220cd77d721.png)

**Comment by JosephMcEvoy** [comment]
Can you try the following:  
`Get-ZoomUsers -APIKey 'ApiKeyGoesHere' -ApiSecret 'ApiSecretGoesHere' -Verbose`  
  
Also for reference on what to copy:  
![image](https://user-images.githubusercontent.com/12501029/78687700-73340900-78c2-11ea-80a3-2741bd885c5f.png)

**Comment by pompushko** [comment]
Do that twice :D

`Get-ZoomUsers : The remote server returned an error: (401) Unauthorized.`

**Comment by JosephMcEvoy** [comment]
Try making a new account and using the credentials from the new account. I just tried this and it is working (with a free/basic account).

**Comment by pompushko** [comment]
@JosephMcEvoy i didnt know how to delete previous one.

I try create from different account - and cannot do that, because already exists.

**Comment by JosephMcEvoy** [comment]
Try making a new Zoom account under a different email.
