### ISSUE TITLE
The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by johnkberry** [JosephMcEvoy/PSZoom#24]
I am receiving this error for all cmdlets despite using the same API Key and API Secret that are working for another app from marketplace.zoom.us/develop/apps/app/credentials.  The API Call Logs at marketplace.zoom.us/user/logs reflect the working app but not calls from PSZoom.  This occurs for the values set globally, as parameters to the cmdlet, and interactively.  I have tested this on both 1.1.83 and 1.11.0.0.  Any suggestions?

```
PS C:\Windows\system32> Get-ZoomMeeting -MeetingId ########### -ApiKey 'verified key' -ApiSecret 'verified secret' -Verbose
VERBOSE: Retrieving Zoom API Credentials.
VERBOSE: Retrieved API Credentials.
VERBOSE: Generating JWT
VERBOSE: Generating Headers
VERBOSE: GET https://api.zoom.us/v2/meetings/########### with 0-byte payload
Get-ZoomMeeting : The remote server returned an error: (401) Unauthorized.
At line:1 char:1
+ Get-ZoomMeeting -MeetingId ########### -ApiKey 'verified key ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-ZoomMeeting
```

**Comment by JosephMcEvoy** [comment]
Confirm your API key and secret haven't changed. Confirm your account is still valid to interface with the API. Possibly reach out to Zoom for further assistance. The cmdlet is working on my machine (ver 1.11.0.0)

**Comment by johnkberry** [comment]
No luck, even after regenerating the secret. PowerShell 7 gives a little more context:

```
Line |
  75 |  … $response = Invoke-RestMethod -Uri $request.Uri -Headers $headers -Bo …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"code":124,"message":"Access token is expired."}
```

**Comment by JosephMcEvoy** [comment]
Is your system time correct?

**Comment by johnkberry** [comment]
Bingo, domain time and joined clients are about 100 seconds off.  Thanks for the tip.
