### ISSUE TITLE
API Token expires when using pipelines to perform time-consuming operations.

### ISSUE THREAD

**Issue by mkht** [JosephMcEvoy/PSZoom#26]
The current implementation of PSZoom creates an API token with a 30-second expiration time in the `Begin` block and uses it in the `Process` block.

This seems to be a reasonable implementation, but when using a pipeline to process a large number of objects, the token expires without being processed within 30 seconds and a 401 error occurs.
Since my organization deals with a large number of Zoom users, we have actually faced this problem.

Let's come up with a solution.
I propose three plans.

### Plan 1: Create a new token every time you perform an API request.
This is not very smart, as it will generate a lot of tokens, but it is a simple way.
This will not be difficult to implement since we only need to move the process of creating the token from the `Begin` block to the `Process` block.

### Plan 2: Check the token expiration date before executing the API request, and update the token if it has expired.
Record the timestamp when the token was generated and compare it with the current timestamp before executing the request. 
I expect the processing time to be faster than generating the token every time.

### Plan 3: Extend the token expiration date.
The current expiration time is 30 seconds, but we will extend it.
This is the easiest to implement, but not the most essential solution.
Because it is impossible to predict the processing time in advance.

@JosephMcEvoy , Which plan do you think is better?
Whichever plan the owner chooses (or rejects), I will follow it. I can also do the implementation and send a pull request.

(Sorry for the machine translated English. My native language is not English.)

**Comment by JosephMcEvoy** [comment]
I am leaning towards option #2. I am not sure how #2 would be implemented. Would you move the New-ZoomHeaders to the process block, then create some logic around it in New-ZoomHeaders? Something like:

`if ((get-date(Parse-JWTToken -token (New-ZoomApiToken -ApiKey 123 -ApiSecret 456)).exp) -lt (get-date)) {New-ZoomHeaders}`

Potentially a fourth option, exposing the -ValidForSeconds parameter to all public functions then passing it to New-ZoomHeaders which will pass it to New-ZoomToken.  

Thank you for taking the time to explain the problem and some solutions. No problems with the English, it's actually near perfect. It is easier to understand than most native speakers.

**Comment by JosephMcEvoy** [comment]
I replaced Invoke-RestMethod with Invoke-**Zoom**RestMethod, across all of the \Public\ functions. You can implement New-ZoomHeaders within Invoke-ZoomRestMethod. This should greatly reduce the number of lines of code.

You would also have to remove New-ZoomHeaders from the Begin blocks, as well as remove the -Headers parameter from Invoke-ZoomRestMethod calls.

**Comment by mkht** [comment]
An example implementation of Plan2 would look like this code.
In the Process block, it decodes the Header to get the expiration date and compare it with the current time.
Only if the token has expired, it calls `New-ZoomHeaders` to update the Header and token.

```PowerShell
function Get-ZoomUser {
    [CmdletBinding()]
    param (
        [Parameter(
            Mandatory = $True, 
            Position = 0, 
            ValueFromPipeline = $True,
            ValueFromPipelineByPropertyName = $True
        )]
        [Alias('email', 'emailaddress', 'id', 'user_id', 'ids', 'userids', 'emails', 'emailaddresses', 'host_id')]
        [string[]]$UserId,

        [ValidateSet('Facebook', 'Google', 'API', 'Zoom', 'SSO', 0, 1, 99, 100, 101)]
        [Alias('login_type')]
        [string]$LoginType,

        [ValidateNotNullOrEmpty()]
        [string]$ApiKey,

        [ValidateNotNullOrEmpty()]
        [string]$ApiSecret
    )

    begin {
        #Generate Header with JWT (JSON Web Token) using the Api Key/Secret
        $headers = New-ZoomHeaders -ApiKey $ApiKey -ApiSecret $ApiSecret
    }

    process {
        foreach ($id in $UserId) {
            $request = [System.UriBuilder]"https://api.zoom.us/v2/users/$id"

            if ($PSBoundParameters.ContainsKey('LoginType')) {
                $LoginType = switch ($LoginType) {
                    'Facebook' { 0 }
                    'Google' { 1 }
                    'API' { 99 }
                    'Zoom' { 100 }
                    'SSO' { 101 }
                    Default { $LoginType }
                }
                $query = [System.Web.HttpUtility]::ParseQueryString([String]::Empty)  
                $query.Add('login_type', $LoginType)
                $Request.Query = $query.ToString()
            }
        
            # Update the token if it has expired.
            $CurrentUnixTime = ((Get-Date) - (Get-Date '1970/1/1 0:0:0 GMT')).TotalSeconds
            $TokenPayload = ($headers.authorization -split '\.')[1]
            $TokenExpireTime = [int]((ConvertFrom-Json ([System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($TokenPayload + '=' * (4 - $TokenPayload.Length % 4))))).exp)
            if ($CurrentUnixTime -ge $TokenExpireTime) {
                $Headers = New-ZoomHeaders -ApiKey $ApiKey -ApiSecret $ApiSecret
            }

            $response = Invoke-ZoomRestMethod -Uri $request.Uri -Headers $headers -Method GET
            
            Write-Output $response
        }
    }
}
```

**Comment by mkht** [comment]
Your plan to change it to create a Header in the Invoke-ZoomRestMethod looks practically the same as implementing my plan 1.
I think it's an attractive plan because it keeps the code simple.

Compared to my plan 2, I think there is a little more processing overhead due to the higher number of token generation. However, in my test, the processing time was about 1 second for 1000 runs, so it may not be a problem.

Do we go ahead with this plan?

**Comment by JosephMcEvoy** [comment]
What do you think about having the token expiry logic put into Invoke-RestMethod? You could use $script:headers (I think) to update the token if it has expired.

**Comment by mkht** [comment]
Good idea, but the update by `$script:Headers` probably won't work. (I haven't tested it)
To update the caller's variables, you need to pass a variable by reference

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_ref

Here is a simple implementation example. I have omitted all the parts that are not necessary for the example, but it is code that works.
Note that $Headers is preceded by a `[ref]` modifier.



```PowerShell
function Invoke-ZoomRestMethod {
    [CmdletBinding(DefaultParameterSetName = 'Default')]
    param (
        $Method,
        [uri]$Uri,
        [ref]$Headers
    )

    # Update the token if it has expired.
    $CurrentUnixTime = ((Get-Date) - (Get-Date '1970/1/1 0:0:0 GMT')).TotalSeconds
    $TokenPayload = ($Headers.Value.authorization -split '\.')[1]
    $TokenExpireTime = [int]((ConvertFrom-Json ([System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($TokenPayload + '=' * (4 - $TokenPayload.Length % 4))))).exp)
    if ($CurrentUnixTime -ge $TokenExpireTime) {
        $Headers.Value = New-ZoomHeaders -ApiKey $ApiKey -ApiSecret $ApiSecret
    }
    
    $params = @{
        Method  = $Method
        Uri     = $Uri
        Headers = $Headers.Value
    }

    try {
        $response = Invoke-RestMethod @params
    }
    catch {
        #---- (ellipsis) ----
    }
    Write-Output $response
}

# ---------------------------------------------------------------- #
function Get-ZoomUser {
    [CmdletBinding()]
    param (
        [string[]]$UserId,
        [string]$ApiKey,
        [string]$ApiSecret
    )

    begin {
        #Generate Header with JWT (JSON Web Token) using the Api Key/Secret
        $headers = New-ZoomHeaders -ApiKey $ApiKey -ApiSecret $ApiSecret
    }

    process {
        foreach ($id in $UserId) {
            $request = [System.UriBuilder]"https://api.zoom.us/v2/users/$id"
 
            $response = Invoke-ZoomRestMethod -Uri $request.Uri -Headers ([ref]$Headers) -Method GET
            
            Write-Output $response
        }
    }
}
```

**Comment by JosephMcEvoy** [comment]
If you agree with the implementation you have described most recently, then let's proceed with modifying invoke-zoomresponse to include the expiry logic and updating of headers.

**Comment by mkht** [comment]
Okay, I will start to modify the `Invoke-ZoomRestMethod` based on the agreement. I will create a PR in a few days, so please wait a bit.

**Comment by JosephMcEvoy** [comment]
Good work on this. Your efforts are much appreciated. I should have this shipped out to Powershell Gallery this week.
