### ISSUE TITLE
Improve Get-ZoomUsers

### ISSUE THREAD

**Issue by pompushko** [JosephMcEvoy/PSZoom#28]
Hello

Could you add search parameter **type**?
Thank you :)

**Comment by JosephMcEvoy** [comment]
Are you talking about the role_id request parameter? https://marketplace.zoom.us/docs/api-reference/zoom-api/users/users

**Comment by pompushko** [comment]
Hello @JosephMcEvoy 
Nope. Type: users type plan

**Comment by JosephMcEvoy** [comment]
The type parameter is not part of the request schema for this API endpoint and therefore would have to be implemented by someone at Zoom. Correct me if I am missing something.

If you need to return a particular type from the list of users, it's pretty easy with PSZoom and Powershell:
get-zoomusers -allpages | ? type -eq 2

**Comment by pompushko** [comment]
Thank you. I know that variant, but if you have 500+ users... too hard do that fast :)

But its okay. If not possible - we can close that ticket.
