### ISSUE TITLE
409 conflict yet user isn't listed

### ISSUE THREAD

**Issue by izirdum-FGSD** [JosephMcEvoy/PSZoom#29]
I'm trying to automate our user creation. For some user accounts it works just fine, but for some users, I'm consistently getting an error they can't be created:

` Invoke-ZoomRestMethod : The remote server returned an error: (409) Conflict. 
At C:\Program Files\WindowsPowerShell\Modules\pszoom\1.12.0.0\Public\Users\New-ZoomUser.ps1:166 char:25
+ ... $response = Invoke-ZoomRestMethod -Uri $request.Uri -Headers ([ref]$H ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (https://api.zoom.us/v2/users:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : 409,Invoke-ZoomRestMethod 
`

Looking for the user in the list of users on the web portal doesn't show them at all. How can I find out what is preventing the user creation? (I even tried a remove-zoomuser action on the account in question, and I get a 404 not found error).

Thank you.

**Comment by JosephMcEvoy** [comment]
Users can register for Zoom under their non-personal email (i.e. company or school email). This can create a conflict, despite the user account not already being in your Zoom account. Could this be an issue? See [this support page](https://support.zoom.us/hc/en-us/articles/203395207) for requiring SSO on a domain.

**Comment by zirdum** [comment]
Argh... I forgot that some of our users did this before we had a chance to put them in Zoom ourselves.

Thank you!
