### ISSUE TITLE
-enforce_login and -enforce_login_domains deprecated

### ISSUE THREAD

**Issue by queks** [JosephMcEvoy/PSZoom#3]
In the Zoom API to create/update new meetingsi, it says that flags -enforce_login and -enforce_login_domains are deprecated, and to use authentication configurations instead.

**Comment by JosephMcEvoy** [comment]
Thank you for bringing that to my attention. I'll make some changes and push them out.

**Comment by JosephMcEvoy** [comment]
Completed changes.
