### ISSUE TITLE
How do we set the role of a user?

### ISSUE THREAD

**Issue by izirdum-FGSD** [JosephMcEvoy/PSZoom#30]
The API seems to have a way to update the role (https://marketplace.zoom.us/docs/api-reference/zoom-api/roles/updaterole) but I can't find the corresponding PSZoom command to update it. Is there a way to do this with PSZoom?

Thank you.

**Comment by JosephMcEvoy** [comment]
You can try and use PSZoom/Public/Utils/Invoke-ZoomRestMethod.ps1. This hasn't bee added to PowerShell Gallery, yet. Ideally you would open up a pull request and add the functionality.

**Comment by izirdum-FGSD** [comment]
I see... I was actually meaning to ask how to update a user's role (https://marketplace.zoom.us/docs/api-reference/zoom-api/roles/addrolemembers), but I imagine it's the same answer.

**Comment by izirdum-FGSD** [comment]
Woohoo.. it's a steep learning curve, but thank you for making it less steep!

**Comment by izirdum-FGSD** [comment]
Actually... one quick question... I got it to list the roles using this:
$request = [System.UriBuilder]"https://api.zoom.us/v2/roles/{roleId}/members"
Invoke-ZoomRestMethod -Uri $request.Uri -ApiKey $($ZoomApiKey) -ApiSecret $($ZoomApiSecret) -Method GET 

So building on that I can set the roles using this I imagine, but I'm not sure how to add the userID to this so that it updates a specific user's role?

$request = [System.UriBuilder]"https://api.zoom.us/v2/roles/RoleIDGoesHere/members"
Invoke-ZoomRestMethod -Uri $request.Uri -ApiKey $($ZoomApiKey) -ApiSecret $($ZoomApiSecret) -Method POST

**Comment by izirdum-FGSD** [comment]
Ah, figured it out... I added  -Body '{"members":[{"id":"MemberIDHere"}]}'  and it worked!! Thanks so much for creating this!

**Comment by JosephMcEvoy** [comment]
Something like this (code not verified):

```
$roleid = 'admin'
$members = @(@{id = 'izirdum'},@{id = 'izirdumsfriend'})
$request = [System.UriBuilder]"https://api.zoom.us/v2/roles/$($roleid)/members"
$requestBody = @{
members = $members
}

$requestBody = $requestBody | ConvertTo-Json
 Invoke-ZoomRestMethod -Uri $request.Uri -Headers ([ref]$Headers) -Body $requestBody -Method POST -ApiKey $ApiKey -ApiSecret $ApiSecret
```

**Comment by JosephMcEvoy** [comment]
> 
> 
> Ah, figured it out... I added -Body '{"members":[{"id":"MemberIDHere"}]}' and it worked!! Thanks so much for creating this!

Nice work. You're welcome.
