### ISSUE TITLE
Missing Functions.

### ISSUE THREAD

**Issue by DamagedDingo** [JosephMcEvoy/PSZoom#31]
Not sure if these were removed on purpose or not but the following are missing 
Get-DashboardZoomRooms.ps1
Get-ZoomRoomDevices.ps1

if you want to restore them i have them in my fork.
https://github.com/DamagedDingo/PSZoom/tree/master/PSZoom/Public/Rooms

**Comment by JosephMcEvoy** [comment]
These were not removed on purpose. I have re-added them. I changed name to Get-ZoomRoomsDashboard to keep with the other cmdlets. I will update PowerShell Gallery.

**Comment by DamagedDingo** [comment]
Thanks we finally went live today and when i ran my scripts they all failed! 😄

**Comment by JosephMcEvoy** [comment]
> 
> 
> Thanks we finally went live today and when i ran my scripts they all failed! 😄

Sorry about that. If you have an example that might be good for the Examples folder maybe consider sharing it. :)
