### ISSUE TITLE
Zoom Phone

### ISSUE THREAD

**Issue by mcbmoreno** [JosephMcEvoy/PSZoom#34]
Thanks a lot for creating this.  Is it possible to add a script like the Get-ZoomUser script for Zoom Phone user settings?

**Comment by JosephMcEvoy** [comment]
Hello,

You are welcome to open up a pull request. You can also use [Invoke-Zoom-RestMethod](https://github.com/JosephMcEvoy/PSZoom/blob/master/PSZoom/Public/Utils/Invoke-ZoomRestMethod.ps1).

**Comment by mcbmoreno** [comment]
Invoke-ZoomRestMethod  worked perfect.  Thanks a lot for your help.
