### ISSUE TITLE
Problem with user-update in another language

### ISSUE THREAD

**Issue by xgadzilax** [JosephMcEvoy/PSZoom#39]
Hello!)
user-update works fine if you pass names in English to the parameters (-FirstName and -LastName), but for the Russian language (which I need) this does not work. The script is executed successfully, but in the end the user has characters instead of a name: ?????

Example request:
`Update-ZoomUser -UserId 'test123@mydomain.ru' -FirstName 'Александр' -LastName 'ded'` 

![user](https://user-images.githubusercontent.com/28839074/125648928-597b9f82-17ad-4791-b1fa-b3612aa195f1.png)

I could not solve this problem on my own, I ask for your help

**Comment by JosephMcEvoy** [comment]
I am not sure what is wrong. It could have to do with the content-type, which is set in [New-ZoomHeaders](https://github.com/JosephMcEvoy/PSZoom/blob/master/PSZoom/Private/New-ZoomHeaders.ps1) then passed to Invoke-ZoomRestMethod, which calls Invoke-RestMethod. It could also have to do with how PowerShell and Zoom interpret the characters. Possibly a combination of the two.  

 @mkht may have some experience with this as he may be using non-English characters.

Here is the simplified relevant bits of a code to help you in seeking help outside of Github:  

```
$Token = New-Jwt -Algorithm 'HS256' -type 'JWT' -Issuer $Credentials.ApiKey -SecretKey $Credentials.ApiSecret -ValidforSeconds $ValidforSeconds
$FirstName = 'Vlad'
$LastName = 'Путин'
$Headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$Headers.Add('content-type' , 'application/json')
$Headers.Add('authorization', 'bearer ' + $Token)
$Request = [System.UriBuilder]"https://api.zoom.us/v2/users/$user"
$RequestBody = @{
    'first_name'    = $FirstName
    'last_name'     = $LastName
}
$RequestBody = $RequestBody | ConvertTo-Json  
Invoke-RestMethod -Uri $request.Uri -Headers ([ref]$Headers) -Body $requestBody -Method PATCH
```

**Comment by mkht** [comment]
This issue is also reproduced in my language, Japanese. (I hadn't noticed this bug until now.)

The is caused by not specifying a charset in the ContentType parameter of the Invoke-RestMethod. if it does not specify, PowerShell seems to implicitly use ISO-8859-1 encoding, which does not support non-Latin characters are not supported.

Try this code. This worked for my environment.
```powershell
$Token = New-ZoomApiToken -ApiKey $Global:ZoomApiKey -ApiSecret $Global:ZoomApiSecret
$FirstName = 'Vlad'
$LastName = 'Путин'
$Request = [System.UriBuilder]"https://api.zoom.us/v2/users/$user"
$RequestBody = @{
    'first_name'    = $FirstName
    'last_name'     = $LastName
}
$RequestBody = $RequestBody | ConvertTo-Json  
Invoke-RestMethod -Uri $request.Uri -Headers @{'authorization' = ('bearer ' + $Token)} -Body $requestBody -Method PATCH -ContentType 'application/json; charset=utf-8'
```

Setting the default value of the ContentType parameter in Invoke-ZoomRestMethod to `'application/json; charset=utf-8'` may be a solution, but we need to check for any bad side effects.
If you give me a few days, I can provide a pull request, what do you think, @JosephMcEvoy

**Comment by JosephMcEvoy** [comment]
Good analysis and summarization. If you have the bandwidth, proceed. Depending on testing, I/we may have to consider adding -ContentType as another parameter for all cmdlets. Thank you for your help, as always.

**Comment by xgadzilax** [comment]
@mkht , @JosephMcEvoy Thank you very much! Спасибо!)) 
I can continue to work with my project !!!
For me `-ContentType 'application / json; charset = utf-8 '`works too))
