### ISSUE TITLE
Get-ZoomDailyUsageReport is a dup of Get-ZoomActiveInactiveHostReports

### ISSUE THREAD

**Issue by SmallBatches** [JosephMcEvoy/PSZoom#4]
I was look for the Daily Usage Report and it looks like it has the same code as the ActiveInactiveHostReports.

Great job on this, btw. REALLY Helpful!

**Comment by JosephMcEvoy** [comment]
Thanks for bringing that to my attention. I'll have it fixed for the next release. It's good to hear someone is finding it useful! Please feel free to star the repo and help bring some attention to it.

**Comment by JosephMcEvoy** [comment]
This has been resolved.
