### ISSUE TITLE
Get-ZoomAllMeetings returns 22 records every time

### ISSUE THREAD

**Issue by philliplyle** [JosephMcEvoy/PSZoom#45]
There's some sort of issue with the Get-ZoomAllMeeting, which is exactly what I happened to need for a new project.  Every time I run it, it only returns 22 meeting records for a period of time despite some months having thousands of records.     For the same period, Get-ZoomAccountRecordings returns over 1000 recordings, so it's not an access issue.  I have tried date range variations, but it's always 22. 
 Any ideas?

Here's an example:

$ToDate = "2021-06-30";
$FromDate = "2021-06-01";

get-zoomallmeetings -PageSize 300 -From $FromDate -To $ToDate 

Results:

from            : 2021-06-01
to              : 2021-06-30
page_count      : 1
page_size       : 300
total_records   : 22
next_page_token :
meetings        : {@{uuid=AOs0l8fMiRCy9IbHi3TgarQ==; id=91943221; topic=Joe Schmoe's Zoom Meeting; host=Joe
             

This works fine for recordings:

get-zoomaccountrecordings -AccountID me -PageSize 300 -From $FromDate -To $ToDate

from            : 2021-06-01
to              : 2021-06-30
page_size       : 300
total_records   : 1275

**Comment by JosephMcEvoy** [comment]
This cmdlet does not make use of the 'type' parameter. I'll fix it. Zoom is filling it in for you automatically as 'live', as in meetings happening at the current time. From the Zoom documentation:  

> 
>     "type": {
>       "type": "string",
>       "default": "live",
>       "enum": [
>         "past",
>         "pastOne",
>         "live"
>       ],
>       "description": "Specify a value to get the response for the corresponding meeting type. The value of this field can be one of the following:<br> <br>`past` - Meeting that already occurred in the specified date range.<br>`pastOne` - Past meetings that were attended by only one user. <br>`live` - Live meetings.<br><br>\n\nIf you do not provide this field, the default value will be `live` and thus, the API will only query responses for live meetings."
>     }

**Comment by JosephMcEvoy** [comment]
I have updated the help to reflect this information. I have also added additional examples.

**Comment by philliplyle** [comment]
@JosephMcEvoy Thanks for the quick response!  It's now working as expected.  Great find - I didn't even consider I was seeing live results.

The "Type" parameter appears to be case sensitive, however.  I originally did upper-case Past and it was defaulting to live results.  So that might be one suggested tweak, unless it's desired.
