### ISSUE TITLE
Issue with Invoke-restmethod

### ISSUE THREAD

**Issue by jasonlshelton** [JosephMcEvoy/PSZoom#46]
I really like these wrappers, thank you for writing them. 

When I do a simple get-zoomuser (probably all commands, but I'm testing with that one.) It hits the Invoke-ZoomRestMethod.ps1 and fails at line 149 where it calls Invoke-restmethod with the error 

> You cannot call a method on a null-valued expression.

and falls into the catch block. I have this exact script working on a different computer  (simply copy/paste since it's 4 lines, including the import) so I'm not sure why this one isn't working. 

Clearly @params has a null in there somewhere, but I'm over my head trying to figure it out.

**Comment by JosephMcEvoy** [comment]
Hi @jasonlshelton, I'm glad you're finding it useful.  

I suppose it could be a PowerShell version problem? Could you post your full code, PowerShell version, and maybe version of PSZoom if not on latest.

**Comment by jasonlshelton** [comment]
My code is as simple as you can get.

```
import-module PSZoom

$Global:ZoomApiKey    = '<my key>'  
$Global:ZoomApiSecret = '<my secret>'  


get-zoomuser -verbose <user email address>

```
```
PS C:\Scripts\powershell-scripts> $PSVersionTable


Name                           Value                                                                                                                                                                                                                             
----                           -----                                                                                                                                                                                                                             
PSVersion                      5.1.14393.4583                                                                                                                                                                                                                    
PSEdition                      Desktop                                                                                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                                           
BuildVersion                   10.0.14393.4583                                                                                                                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                                               
SerializationVersion           1.1.0.1           
```

It looks like @params is empty when it tries to call Invoke-restmethod

`$response = Invoke-RestMethod @params`

**Comment by SpectreGadget** [comment]
You need to add the ApiKey and ApiSecret to your get-zoomuser command.
 get-zoomuser  -ApiKey $global:ZoomApiKey -ApiSecret $global:ZoomApiSecret
-verbose <user email address>

Jim

**Comment by JosephMcEvoy** [comment]
@SpectreGadget, the cmdlet will look in the Global scope automatically if the API Key/Secret are not provided.  
  
I'm scratching my head as to why it isn't working. On the computer it is working on, is it running the same exact version of PowerShell? Maybe try updating PowerShell? Could also have to force PowerShell to use TLS1.2 `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`. What else...you could try running it in PowerShell Core and see if it works there.  

It's working for me on 5.1 and 7. Here's my 5.1 PS Version:
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1151
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1151
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by jasonlshelton** [comment]
hey, that was it, the TLS1.2. I added that line and it works perfectly.  So I'm guessing something is messed up in my crypto libs install on this server. Thank you, I would not have thought of that.
