### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jasonlshelton** [JosephMcEvoy/PSZoom#49]
I've noticed that if the user does not exist in zoom, the return is a 404 which is then just dumped to the output. It would be nice to have either a "User not found" message or just no return at all.

**Comment by JosephMcEvoy** [comment]
Currently a user not found returns a 404 Error to the error stream, categorized as `InvalidOperation`. I am not understanding what your suggested feature request is. If you don't want to see the errors, use ` -ErrorAction SilentlyContinue`.

Errors are handled in \PSZoom\Public\Utils\Invoke-ZoomRestMethod.ps1, if you want to see how it is written.

```
Invoke-ZoomRestMethod : The remote server returned an error: (404) Not Found. 
At ..\PSZoom\Public\Users\Get-ZoomUser.ps1:103 char:25
+ ... $response = Invoke-ZoomRestMethod -Uri $request.Uri -Headers ([ref]$H ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (https://api.zoo...y@xyz.com:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : 404,Invoke-ZoomRestMethod
```

**Comment by jasonlshelton** [comment]
Didn't know about the ErrorAction switch, so uuuhhhh, nevermind :-)
