### ISSUE TITLE
Store API Key/Secret in module scope variable

### ISSUE THREAD

**Issue by b-dasass** [JosephMcEvoy/PSZoom#54]
Storing the API Key/Secret in module scope variable instead of the global scope would protect them a little bit more. Right now everything running in PowerShell could see these variables.

Tagging my personal account @sassdawe to have a look at weekend and if time allows send a PR

**Comment by JosephMcEvoy** [comment]
Hi, if I can lead you in the right direction: you should only have to modify PSZoom/Private/Get-ZoomApiCredentials.ps1 to make this work.

**Comment by sassdawe** [comment]
Thank you! I haven't spent enough time looking at it just yet, but think we'll need a Set function as well. Plus switch all the $Global: variables to module scoped. 
I also want to create some Pester tests for the changes I'm going to introduce. If you don't mind.
