### ISSUE TITLE
Issue with adding user to IM Group

### ISSUE THREAD

**Issue by izirdum-FGSD** [JosephMcEvoy/PSZoom#56]
I previously wrote some code to add the user to the IM group. It was working fine for some time, but it stopped working and I'm not sure what's changed?

My code is as follows:
```
function Set-StaffZoomIMGroup($UserId, $UserEmail)
{
    $groupId = 'IMGroupIDGoesHere'
    $members = @(@{id = "$UserId"})
    $request = [System.UriBuilder]"https://api.zoom.us/v2/im/groups/$groupId/members"
    $requestBody = @{
    members = $members
    }
    $requestBody = $requestBody | ConvertTo-Json
    
    Invoke-ZoomRestMethod -Uri $request.Uri -Body $requestBody -Method POST -ApiKey $($ZoomApiKey) -ApiSecret $($ZoomApiKey)
}
```

The error I'm getting is 
The property 'Key' cannot be found on this object. Verify that the property exists.
At C:\Powershell\ZoomManualStaff.ps1:178 char:21
+ ...         if ($Parameters.ContainsKey($Obj.$Key) -or -not [string]::IsN ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
 
That line is referenced in the "Invoke-ZoomRestMethod" function.

Any tips?

**Comment by JosephMcEvoy** [comment]
This is already a function created in PSZoom, it's called Add-ZoomGroupMember.ps1. Please let me know if it works or not.

```
.EXAMPLE
Add a single user to a single group.
$GroupId = ((Get-ZoomGroups) | where-object {$_ -eq 'Light Side'}).id
Add-ZoomGroupMembers -group $GroupID -Email okenobi@lightside.com, lskywalker@lightside.com

.EXAMPLE
Add users to a single group.
Get-ZoomGroups | where-object {$_ -eq 'Dark Side'} | Add-ZoomGroupMembers -email 'dvader@sith.org','dsidious@sith.org'

.EXAMPLE
Add a single user to all groups matching 'Side'.
Get-ZoomGroups | where-object {$_ -like '*Side*'} | Add-ZoomGroupMembers -email 'askywalker@theforce.com'
```

**Comment by izirdum-FGSD** [comment]
I'm sorry, but that module is referring to Groups, not IMGroups (I tried using the IMGroup ID but it rejects it saying it's 'not found')

Add-ZoomGroupMemebers is referring to "https://api.zoom.us/v2/groups/$Id/members"

The IM groups that I'm talking about above are referring to this API: "https://api.zoom.us/v2/im/groups/$Id/members" ( https://marketplace.zoom.us/docs/api-reference/zoom-api/im-groups/imgroupmemberscreate )

**Comment by izirdum-FGSD** [comment]
My bad... I updated to 1.16, but didn't restart the powershell ISE (even after removing and unloading the old package)... Restarting the ISE fixed it.

**Comment by JosephMcEvoy** [comment]
@izirdum-FGSD Since this is practically the same function, with a different URI, I created a new function:  
PSZoom/Public/IMGroups/Add-ZoomIMDirectoryGroupMembers.ps1  

Could you test?

**Comment by izirdum-FGSD** [comment]
It doesn't quite work. It'll run without erroring, but it returns

`ids added_at            
--- --------            
    2021-09-30T20:51:57Z`

The ids are blank in the list above, so it seems it didn't add anything (and the user doesn't show up in the list).

The commands I tried to run (same results (doesn't add the user to the IM group)):
Add-ZoomIMDirectoryGroupMembers -groupid $groupid -MemberId $ZoomAccountUser.id
Add-ZoomIMDirectoryGroupMembers -groupid $groupid -MemberId $ZoomAccountUser.id -email $email
Add-ZoomIMDirectoryGroupMembers -groupid $groupid -email $email

**Comment by izirdum-FGSD** [comment]
I found the issue... in your file on line 78:
       if ($PSBoundParameters.ContainsKey('MemberIds')) {

MemberIds should be just MemberId:
       if ($PSBoundParameters.ContainsKey('MemberId')) {

**Comment by izirdum-FGSD** [comment]
I started a pull-request, but I've never done one before, so I'm not sure if I'm doing it right.
