### ISSUE TITLE
Random 404 error when deleting recording file

### ISSUE THREAD

**Issue by IdolR** [JosephMcEvoy/PSZoom#6]
Hi there and thanks again for this useful tool

I am using PSZoom to download and delete Zoom cloud recordings, however out of about 2,000 successfully deleted recordings,  38, which show "completed" status, cannot be deleted no matter what I try, PSZoom will throw an exceptions such as

```
Remove-ZoomMeetingRecordingFile : The remote server returned an error: (404) Not Found.
At C:\Temp\zoom\zoomBackup.ps1:83 char:9
+         Remove-ZoomMeetingRecordingFile -MeetingId $zoomItem.meeting_ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Remove-ZoomMeetingRecordingFile
```
Running script within VSCode, I could help debugging data, if required

**Comment by JosephMcEvoy** [comment]
I am not sure why this is happening. Is there any commonality between the files? Date, meeting ID, characters used in the file IDs?

You could also try the Remove-ZoomMeetingRecordings function.

**Comment by IdolR** [comment]
Commonality: 
- all meeting ids contain at least one slash character ( '/' )

**Comment by IdolR** [comment]
This issue is being followed by Zoom support now
