### ISSUE TITLE
Remove-zoomspecificuserassistant doesn't allow you to remove assistant based on email address

### ISSUE THREAD

**Issue by Tuxhedoh** [JosephMcEvoy/PSZoom#65]
Seems most of the user specific cmdlets allow you to use an email address instead of id. 

Running
`remove-zoomspecificuserassistant myemail@address.com assistantemail@address.com` doesn't provide any error or feedback, but also doesn't seem to work. 
`remove-zoomspecificuserassistant myemail@address.com assistantid` does work. 

Not sure if this is a bug or not.

**Comment by JosephMcEvoy** [comment]
This is by (Zoom's) design. See [https://marketplace.zoom.us/docs/api-reference/zoom-api/methods#tag/Users/operation/userAssistantDelete](https://marketplace.zoom.us/docs/api-reference/zoom-api/methods#tag/Users/operation/userAssistantDelete).
