### ISSUE TITLE
Change Phone User’s Extension Number

### ISSUE THREAD

**Issue by cpietrucha** [JosephMcEvoy/PSZoom#73]
Hey Joseph,
I am currently using your new 2.0 script with Powershell and trying to automate zoom phone user creation and updates based on Active Directory attributes that I pass through the scripts provided. I noticed that you have a few Get-ZoomPhonexxx.ps1 scripts but there are no Update-ZoomPhonexxx.ps1 scripts to update Zoom Phone User settings. I am currently looking to update the extension number on the zoom phone side based on the telephoneNumber attribute in AD for each user but didn’t see any parameter for this in any of the scripts provided. Any insight would be much appreciated. Thanks

**Comment by JosephMcEvoy** [comment]
Hi,  

You can use `Invoke-ZoomRestMethod` to do this. Otherwise I suggest to fork, make a feature branch, commit, and push. We're up to 12 contributors now, many of whom haven't contributed publicly to a repo before this, so don't be shy!
