### ISSUE TITLE
Cannot bind argument to parameter 'InputObject' because it is null

### ISSUE THREAD

**Issue by chappers77** [JosephMcEvoy/PSZoom#77]
Hi

I've just installed your module and found the above issue when running Connect-PSZoom.
It turns out the issue is when the machine doesn't have IE installed and changing the "$response = Invoke-WebRequest -uri $uri -headers $headers -Method Post" line in New-OAuthToken to include "-UseBasicParsing" resolves the issue.

Just thought I would let you know as I know IE is depricated and a lot of people and companies will be getting rid of it.

HTH

Matt

**Comment by IdahoVandal** [comment]
This is an example of the error which is generated from the Invoke-WebRequest.

> The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
