### ISSUE TITLE
new-zoomUser Error 400 bad request

### ISSUE THREAD

**Issue by marcinpolanski** [JosephMcEvoy/PSZoom#81]
![image](https://user-images.githubusercontent.com/119888278/205714013-a6ef42b2-a68e-42ed-88d3-c17e41eed58c.png)

**Comment by PEBKAC89** [comment]
I also have the exact same issue. I only can add a user when I kick-off the New-Zoomuser.ps1 and fill it in the requirements, but not this way how it described in the example.

**Comment by JosephMcEvoy** [comment]
Which version of PSZoom are you running?

**Comment by marcinpolanski** [comment]
I am running 2.0.2.0.
If i run the command with -autocreate and add -password then it works. But the user needs to be a sso user. So i would like to get the -ssocreate to work.

**Comment by JosephMcEvoy** [comment]
Try capitalizing the c in "ssoCreate".

**Comment by marcinpolanski** [comment]
i have noticed that if i create the user using the -autocreate and then try to sign in via sso login it works and changes the user to an sso user automatically once signed in using the sso method. The only thing is that it automatically activated the user. Would be ideal if it sent a verification email to the newly created account. That is how creating a new user via the zoom web app works.

**Comment by JosephMcEvoy** [comment]
You're welcome! Were you able to get it working with -action 'ssoCreate'?

**Comment by marcinpolanski** [comment]
no unfortunately i was not able to create a user with the -ssoCreate option

**Comment by marcinpolanski** [comment]
Also is there a way to update the users manager field? I dont see it under update-zoomuser function... 
And is there a way to change the users license to use zoom one basic and zoom phone basic?

**Comment by PEBKAC89** [comment]
![image](https://user-images.githubusercontent.com/122268943/212926124-e55fb3fe-f6e2-4ee0-b6fd-b6e26fe6f934.png)

Did exactly as the example, but still the same error.
