### ISSUE TITLE
change the "user type"

### ISSUE THREAD

**Issue by marcinpolanski** [JosephMcEvoy/PSZoom#86]
Is there a way to change the user type from zoom one basic to zoom one basic and zoom phone basic? 

![Screenshot 2023-01-27 132136](https://user-images.githubusercontent.com/119888278/215164613-65bc14e7-2f5d-4027-b8c1-c771e755e000.png)

**Comment by andrew-hoggins** [comment]
Hello @marcinpolanski,

You can achieve the above by using the -ZoomPhone Argument on the "Update-ZoomUserSettings" function.
Please see below example.

```powershell
Update-ZoomUserSettings -UserId "user123@tempcompany.com" -ZoomPhone $True
```
