### ISSUE TITLE
Unable to use Update-ZoomMeeting InvalidOperation : (:) [Write-Error], WriteErrorException

### ISSUE THREAD

**Issue by jakalax** [JosephMcEvoy/PSZoom#9]
Hello, 

Thanks you for you great tools.

I begin to use it to manage our meeting, I'm able to create one and get content after, but now that I test the update function I have the following error :

if I type :
`Update-ZoomMeeting -MeetingId '123456789' -Topic 'Petit dejeuner updated' -StartTime '2020-05-17T19:00:00' -Duration 30`

I have the following error :
Update-ZoomMeeting : Le serveur distant a retourné une erreur : (400) Demande incorrecte.
Au caractère Ligne:1 : 1
+ Update-ZoomMeeting -MeetingId '78826924380' -Topic 'Petit dejeuner up ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Update-ZoomMeeting

I try to replace the MeetingId by the uuid, in this case I don't have error, but the meeting is not updated.

I also try to change or remove topic, startime etc without change.

Do you have any idea of what is wrong?

regards,

**Comment by JosephMcEvoy** [comment]
Thank you for pointing this out. There was an issue with how tracking_fields were being handled. I have updated the module. Update to Powershell Gallery coming shortly.

**Comment by JosephMcEvoy** [comment]
This has been fixed. Run Update-Module PSZoom. Please let me know if you are still having issues.

**Comment by jakalax** [comment]
Hello,

Thanks for your time. 

Its works now on my computer to update the subject but not the startime, so if I run the following command :

Update-ZoomMeeting -MeetingId '123456789' -Topic 'New subject' -StartTime '2020-05-25T19:00:00' -Duration 30

"New subject" appear in place of preview Topic, but the StartTime stay the same.

I also try yo redeploy on Azure Automation (from here :https://www.powershellgallery.com/packages/PSZoom/1.1.7), but in this case I still have the original Error 400.

In the meanwhile, on Microsoft 365 Power Automate, I decide to use the official Zoom API, so I didn't need the PowerScript one for the moment.

**Comment by JosephMcEvoy** [comment]
Hi jakalax,

I was seeing the same. I have fixed the issue with the start time. You will have to update.
