### ISSUE TITLE
User accounts not getting created

### ISSUE THREAD

**Issue by AstroFish849** [JosephMcEvoy/PSZoom#96]
I'm using the AOuth option and the Connect-PSZoom -AccountID .... to connect which is working fine.
I send the command for a new user using variables which all work fine:
New-ZoomUser -Action create -Email $email -FirstName $firstName -LastName $lastName -Type 2 -Password $password

The API call log shows status 200 but the user isn't created.
Below is a header response from a test user if it helps:

{
"endpoint": "https://api.zoom.us//v2/users",
"method": "POST",
"response": {
"id": "LpCnjaZHTq6T14T48Akdzg",
"first_name": "John",
"last_name": "Brown",
"email": "John.Brown@domain.com",
"type": 2
},
"response_headers": "{X-RateLimit-Remaining=9983, Cache-Control=no-cache, no-store, must-revalidate, no-transform, X-Content-Type-Options=nosniff, Set-Cookie=zm_aid=""; Domain=.zoom.us; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly, Vary=Origin, Pragma=no-cache, Expires=Thu, 01 Jan 1970 00:00:00 GMT, X-RateLimit-Limit=10000, x-zm-trackingid=v=2.0;clid=us02;rid=WEB_faaac821c56d30136b20134781aaf8b8, X-RateLimit-Category=Light, x-zm-zoneid=VA2}",
"date_time": "2023-08-03T12:34:22.788+00:00",
"request_body": "{ "user_info": { "email": "John.Brown@domain.com", "last_name": "Brown", "first_name": "John", "type": 2, "password": "Password123456!!!" }, "action": "create"}",
"request_headers": "{content-length=318, cdn-loop=cloudflare, cf-ipcountry=GB, cf-ray=7f0e982bbbc3777d-LHR, x-forwarded-proto=https, x-zm-real-ip=83.98.39.66, x-zm-gateway-rcv-time=2023-08-03T12:34:22.765Z, x-zm-web-tk=p51q8t5HyehGDhB, x-forwarded-for=83.98.39.66, 172.71.194.116, 170.114.10.88, 170.114.10.91, 170.114.10.235, 170.114.10.238, 10.7.131.95, x-zm-cf-tk=2b6MSXkuKqg7, x-zm-cross-cluster=1, authorization=******, x-zm-haid=440, x-zm-sidecar-rcv-time=2023-08-03T12:34:22.787Z, cf-visitor={"scheme":"https"}, host=api.zoom.us, connection=close, cf-connecting-ip=83.98.39.66, content-type=application/json; charset=utf-8, x-zm-trackingid=WEB_faaac821c56d30136b20134781aaf8b8, x-zm-cluster-id=us02, x-zm-aid=hpTx5d_TTF-TTrfI2IJOuw, accept-encoding=gzip, user-agent=Mozilla/5.0 (Windows NT; Windows NT 10.0; en-GB) WindowsPowerShell/5.1.17763.3770}",
"request_params": "{}",
"http_status": "201"
}

**Comment by JosephMcEvoy** [comment]
Hello, can you try again with the latest version in PowerShell Gallery?
