### ISSUE TITLE
"Cannot process argument transformation on parameter 'Token'" after updating to 2.0.4.0

### ISSUE THREAD

**Issue by I-FGSD** [JosephMcEvoy/PSZoom#98]
On 2.0.3.0 it works fine. I run Connect-PSZoom and then can run commands like get-zoomuser

After updating to 2.0.4.0:

Connect-PSZoom runs normally (no error messages displayed).

Issuing a command like:
get-zoomuser someEmail@mydomain.com

Invoke-ZoomRestMethod : Cannot process argument transformation on parameter 'Token'. Cannot convert the "System.Security.SecureString" value of type "System.String" to type "System.Security.SecureString".
At C:\Program Files\WindowsPowerShell\Modules\pszoom\2.0.4.0\Public\Users\Get-ZoomUser.ps1:85 char:25
+ ...       $response = Invoke-ZoomRestMethod -Uri $request.Uri -Method GET
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ZoomRestMethod], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Invoke-ZoomRestMethod

I downgraded back to 2.0.3.0 and it's working fine once again.

**Comment by mstreeter06** [comment]
I experience the same issue with 2.0.4.0 and resolved by going back to 2.0.3.0.

Love the module. Much appreciated to everyone!

**Comment by mstreeter06** [comment]
Confirmed the 2.0.4.1 update working. Thank you!
