### ISSUE TITLE
[Query] billing api. Is it possible to query licenses?

### ISSUE THREAD

**Issue by nascentt** [JosephMcEvoy/PSZoom#99]
The module is great, many thanks. It's great for getting and updating users and their license types.  But I can't find a command that shows the number of zoom one business user licenses are available, and need to manually get the web portal to see this before using the commands.  
On the app scope page I see I can add the billing scope but don't see any corresponding pszoom commands.

**Comment by JosephMcEvoy** [comment]
You can use PSZoom/Public/Utils/Invoke-ZoomRestMethod.ps1. Otherwise this is not planned.

**Comment by nascentt** [comment]
> You can use PSZoom/Public/Utils/Invoke-ZoomRestMethod.ps1. Otherwise this is not planned.

Thanks I just saw this reply. I'll see if I can figure out how to do it that way. Cheers.

**Comment by nascentt** [comment]
I wasn't able to get this working.  It's a shame there's no plans to set this up, as without the ability to ensure there are free licenses, it means trying to programmatically assign licenses is flawed as there might be none remaining.
